name: Deploy to Vercel

on:
  push:
    branches:
      - feat/devops/#603-Deploy-Vercel-Actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy to Vercel
        run: vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }} --scope joacks-projects-2ed3f009